export { Produccion } from "./Produccion";
export { materiaprimaURLs } from "./MateriaPrima";
export { productosURLs } from "./Productos";
export { proveedoresURLs } from "./Proveedores";
export { clientesURLs } from "./Clientes";
export { MainURLs } from "./Main";
export { usuariosURLs } from "./Usuarios";
export { ventasURLs } from "./Ventas";
export { comprasURLs } from "./Compras";
